# Generated by Django 5.1.7 on 2025-03-23 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0006_role_employee_created_at_employee_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='mobile',
        ),
    ]
